### ISSUE TITLE
Pace.js implementation ?

### ISSUE THREAD

**Issue by Andrewchs** [ConnorAtherton/loaders.css#12]
Hey there, 

Is there anyway to use this awesome project with pace.js?

Cheers.

**Comment by ConnorAtherton** [comment]
Hi, 

I think creating a custom theme for pace and then specifying somewhere in the theme docs that it has a dependency on loaders.css would be the simplest solution. For this to work well it might require that each animation is minified and can be loaded separately so you only get the one animation you need. 

I'll keep this open and create a pr in the next few days.

**Comment by Andrewchs** [comment]
Sound's great sir. 

Can't wait.

**Comment by netbuffer** [comment]
@ConnorAtherton Is it finished?
