### ISSUE TITLE
Documentation on what browsers this supports

### ISSUE THREAD

**Issue by mansona** [ConnorAtherton/loaders.css#13]
I know i can dig into the code and use caniuse.com to figure this one out but I'm wondering if you know off hand what browsers this supports? 

If so then it would be awesome if you could throw a table into the Readme for quick reference. 

If not then just let me know and I'll jump in and cross reference with caniuse.com and maybe create a PR with the compatibility table :wink:

**Comment by renatn** [comment]
+1

**Comment by ConnorAtherton** [comment]
Great idea. I didn't document exact versions I tested on apart from knowing off hand that all the latest desktop browser versions work.

I'll work on adding a compatibility table tonight unless you want to take it @mansona?
