### ISSUE TITLE
benchmarks

### ISSUE THREAD

**Issue by alanhamlett** [ConnorAtherton/loaders.css#26]
The description says emphasis is on performance, but how does this compare to other libraries (daneden/animate.css@c0abb26ee4a9d320df2ff2da4a133a9fbbe60125) or just an animated gif loader? Both CSS transitions and animated GIF loaders are blocked by JavaScript, but is there some other performance gain from using CSS transition loaders?

**Comment by marcobiedermann** [comment]
@alanhamlett Animated gifs cause the browser to repaint the image on every frame.
CSS animations using `opacity` and `transform` instead do not trigger any repaint which is a huge performance benefit, especially on mobile devices,

**Comment by alanhamlett** [comment]
Ok thanks!
