### ISSUE TITLE
Possible to change speed?

### ISSUE THREAD

**Issue by iggyigner** [ConnorAtherton/loaders.css#30]
These are beyond incredible.  Is there currently a way to access the speed of the loading animation (slower/faster transitions between a given loader's various states)?

**Comment by ConnorAtherton** [comment]
Thanks man! You can overwrite the `animation-duration` property to play around with different transition speeds. Note that some loaders require the time between states and the `animation-delay` to be related so they synchronize at certain parts of the animations. I'd say your best best it to just try things out and break it until you get the effect you want :)

**Comment by iggyigner** [comment]
I love it.  Thanks so much, Connor!
