### ISSUE TITLE
Incorrect animations in FF and IE

### ISSUE THREAD

**Issue by romanr** [ConnorAtherton/loaders.css#31]
ball-clip-rotate and ball-clip-rotate-pulse have bogus scale animation in FF and IE.

**Comment by snhasani** [comment]
until fix this bus, u can remove delay value -> the zero

before: animation: rotate 1s 0 cubic-bezier(.09,.57,.49,.9) infinite;
after: animation: rotate 1s cubic-bezier(.09,.57,.49,.9) infinite;

**Comment by ConnorAtherton** [comment]
Hey @romanr, thanks for bringing this up. Could you elaborate on the meaning of bogus animation in this context? 

Does the scale not work? Is it flickering?

**Comment by digitor** [comment]
I've provided a fix for this in PR 51
