### ISSUE TITLE
Create a scalar factor mixin for creating different size animations

### ISSUE THREAD

**Issue by ConnorAtherton** [ConnorAtherton/loaders.css#35]
cc @jonjaques

**Comment by ConnorAtherton** [comment]
Invalid.

**Comment by mlunoe** [comment]
Why is this invalid?

**Comment by ConnorAtherton** [comment]
I had created this as a potential enhancement but had no practical basis for using it. Most people who I've spoken with either plucked each animation as-is or modified the dimensions of child elements in custom override stylesheets after importing the library. In some cases that might cause specificity problems, but I think it is a good general rule to follow.

Having said that, I would like to extract common dimensions out into variables and allow overrides later, perhaps using CSS custom variables to remove the SASS dependency for other codebases.

**Comment by jonjaques** [comment]
Just chiming in, I've had success with using 2d scale transform.

**Comment by mlunoe** [comment]
Magic! Thank you @jonjaques!

For anybody curious:
```css
.loader-small .loader-inner {
  transform: scale(0.5, 0.5);
}
```

**Comment by scottkidder** [comment]
@jonjaques @mlunoe solution should be in the docs somewhere.

**Comment by LebCit** [comment]
Hello everyone,
First of all, thanks a zillion time @ConnorAtherton for your time, efforts and for sharing this awesomeness.
@jonjaques thanks for  the tip, works like a charm, straightforward and intuitive 👍 
This should in fact be somewhere in the documentation as @scottkidder said.

**Comment by jonjaques** [comment]
@scottkidder @LebCit - #86 be the change in the world you want to see 😄
