### ISSUE TITLE
Small/Large sizing classes

### ISSUE THREAD

**Issue by jonjaques** [ConnorAtherton/loaders.css#4]
Hello, thanks for putting this together - Looks great so far!

Do you see utility in adding some sizing classes? Most of these are appropriate for loading panes or pages currently, but some might work well inside a button or other UI elements.

I'm currently wrapping a React component around this (props for active, type) and a sizing option would be great too. I'll see if I can get to a PR tonight but just wanted to get your thoughts.

**Comment by ConnorAtherton** [comment]
Hi @jonjaques, thanks! I'm glad you like it.

I think it's a great idea. I think we can add a class `.small` that just uses a different size defined in the file.

**Comment by jonjaques** [comment]
Cool, I'll see what I can whip up tonight. Here's the react lib btw: http://jonjaques.github.io/react-loaders/
