### ISSUE TITLE
New chrome update makes animations pulse

### ISSUE THREAD

**Issue by Ewan-GrandSlam** [ConnorAtherton/loaders.css#40]
As of chrome 43, it seems as though the animations will pulse, i.e grow and shrink as they run through the animation.

**Comment by ConnorAtherton** [comment]
Hey @Ewan-GrandSlam, is this all animations or only specific ones? It might be the desired behaviour.

**Comment by Ewan-GrandSlam** [comment]
This seems to be with the following:
ball clip rotate
ball clip rotate pulse
ball clip rotate multiple

 for e.g. the ball clip rotate which never used to grow/shrink (or pulse) is now doing so.

**Comment by ConnorAtherton** [comment]
Okay, thanks for this. I'll look into it this evening and report back :+1:
