### ISSUE TITLE
Angular directive

### ISSUE THREAD

**Issue by the-cormoran** [ConnorAtherton/loaders.css#43]
Not really an issue ;)
For the need of a project, I wrote a directive which is doing basically the same stuff than the JQuery but for Angular.js. I thought it could be useful for some people.

Feel free to check it : https://github.com/the-cormoran/angular-loaders

Thanks for the good work btw.

**Comment by Masadow** [comment]
Didn't see your issue, I did the same thing and submitted #50 .

I did it a bit differently since I kept the original syntax for displaying loaders (i.e. not extra angular things)

**Comment by ConnorAtherton** [comment]
Hey both - thanks for opening this issue. I'm adding both the repo link and the pr link to the README so people can find them.
