### ISSUE TITLE
Can the nth-child(0) match some element ? 

### ISSUE THREAD

**Issue by agileago** [ConnorAtherton/loaders.css#54]
https://github.com/ConnorAtherton/loaders.css/blob/master/loaders.css#L45

this project is very fantasy ! but i find the source code has the nth-child(0) selector . as far as i know.

it can't match any element . why is it exist ?

**Comment by ConnorAtherton** [comment]
Hey @agileago, you're right - good catch! This is an off by one error present in the mixin signatures for some of the animations, e.g. `@mixin ball-pulse-sync($n:3, $start:0) {`. Removing now.
