### ISSUE TITLE
about creating a Meteor package

### ISSUE THREAD

**Issue by 92hackers** [ConnorAtherton/loaders.css#58]
hi,  i  download  your  source code, and  made  a  meteor  package with it, 
because  there is no an  official  one, 
and  i believe  many developers  will love it ,
if  you  are  not willing to see  that,  i  will  remove  it !
and  i  promise  i  will  update  it  when  you publish  a  new  version.
thanks  for  your  hard  work.

**Comment by ConnorAtherton** [comment]
Thanks for doing that! Please post the link here and I will add it to the README
