### ISSUE TITLE
Can not adjust  loader'  size ?

### ISSUE THREAD

**Issue by 92hackers** [ConnorAtherton/loaders.css#59]
i  need  a  smaller  one  loader, 
it's too  big,  is  there  any  ways  to  make  it  smaller ?

**Comment by stuxt** [comment]
![qq 20160111113418](https://cloud.githubusercontent.com/assets/4355192/12226451/4fdd6ddc-b857-11e5-9a34-a09a0c07497a.jpg)

like this!

**Comment by ConnorAtherton** [comment]
Thanks for the demo @stuxt!

**Comment by 92hackers** [comment]
thanks all.
