### ISSUE TITLE
Are there any rules?

### ISSUE THREAD

**Issue by stuxt** [ConnorAtherton/loaders.css#64]
I would like to contribute to the increase in the concentration of load animation, what are the considerations?

**Comment by stuxt** [comment]
Because I found that for a long time there is no update

**Comment by ConnorAtherton** [comment]
Hey @stuxt, the only considerations are that you control the animation using only `transform`s and the `opacity` property for reasons outlined [here](http://www.html5rocks.com/en/tutorials/speed/high-performance-animations/).
