### ISSUE TITLE
Change foreground color?

### ISSUE THREAD

**Issue by Zzzen** [ConnorAtherton/loaders.css#68]
The background color of my page is white, so it becomes invisible.

**Comment by letehaha** [comment]
Changed `background-color` in ur code?

**Comment by Parthchokshi** [comment]
.loader-inner.ball-pulse div{
  background-color: #D32F2F;
}

This works. It is coded per div. The more div's you increase you can put more individual loaders.

So you can also pick each individual ball and color it differently with nth:child property which is amazing.

**Comment by ConnorAtherton** [comment]
@Parthchokshi Thanks for answering this! Yes, the solution is to override any values you have in your stylesheet.
