### ISSUE TITLE
Demo site is not working

### ISSUE THREAD

**Issue by jaspersorrio** [ConnorAtherton/loaders.css#70]
Viewed on **Google chrome**
**Version 54.0.2840.71 (64-bit)**

<img width="1280" alt="screen shot 2016-11-07 at 2 22 34 am" src="https://cloud.githubusercontent.com/assets/10573718/20040375/109cbec6-a491-11e6-99cc-c09889252f44.png">

**Comment by ConnorAtherton** [comment]
Thanks for bringing this to my attention. Fixed now 👍
