### ISSUE TITLE
 Cannot read property 'fn' of undefined

### ISSUE THREAD

**Issue by bradennapier** [ConnorAtherton/loaders.css#73]
Looks like this is failing because it wants JQuery that I don't have.  However, $ is defined because chrome defines it if you are not using JQuery.

```js
  $.fn.loaders = function() {
    return this.each(function() {
      var elem = $(this);
      $.each(divs, function(key, value) {
        if (elem.hasClass(key))
          elem.html(addDivs(value))
      })
    });
  };
```

**Comment by ConnorAtherton** [comment]
We have marked the section in the README as optional, and added the header that it is for jQuery only. If you don't need this helper, can you just not include it in your build and just use the css from this project.
