### ISSUE TITLE
how to resize the size of the loader

### ISSUE THREAD

**Issue by mrmengjun** [ConnorAtherton/loaders.css#76]
I Want to meke the loader littler

**Comment by ConnorAtherton** [comment]
@mrmengjun Not sure which loader you are referring too, but you could try changing the `$ball-size` variable if you are changing a ball loader (although, I suspect it will not affect the overall size of the loader).

Another option, and one I have recommended in the past is to take the methods I have used here, copy the source of whichever loader you want (usually people are after a single loader they can use consistently everywhere) and tweak it to be whatever you want in your own repo/app.
