### ISSUE TITLE
ball-triangle-path not found error

### ISSUE THREAD

**Issue by sudonitin** [ConnorAtherton/loaders.css#98]
![image](https://user-images.githubusercontent.com/29048183/122245061-04e5d000-cee3-11eb-8157-6427b6bd7a51.png)

**Comment by vkhv** [comment]
As you could see file available for path https://github.com/ConnorAtherton/loaders.css/blob/master/src/animations/ball-triangle-path.scss. I don't sure that your postcss-loader able to load true sass code.

**Comment by sudonitin** [comment]
I checked the files loaded via npm.. and the file name is different than `ball-triangle-path.scss`
But never mind I copied the code in my local sass files as a workaround.

**Comment by vkhv** [comment]
well anyway this repo is dead  :)

**Comment by sudonitin** [comment]
Ohh wasn't aware of this😅
